apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cust-deployment
  labels:
    app: assignsrvr
  namespace: default
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: assignsrvr
  template:
    metadata:
      labels:
        app: assignsrvr
    spec:
      containers:
        - name: assignsrvrctr
          image: srikanthduvvuri/assignsrvr:latest
          ports:
            - containerPort: 8080
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cust-rollout
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assignsrvr
  strategy:
    blueGreen:
      activeService: cust-active-service
      previewService: cust-preview-service
      autoPromotionEnabled: true
  template:
    metadata:
      labels:
        app: assignsrvr
    spec:
      containers:
      - name: assignsrvrctr
        image: srikanthduvvuri/assignsrvr_r1:latest
        ports:
        - containerPort: 8
---
apiVersion: v1
kind: Service
metadata: 
  name: cust-active-service
  namespace: default
spec:
  selector:
    app: assignsrvr
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata: 
  name: cust-preview-service
  namespace: default
spec:
  selector:
    app: assignsrvr
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort