apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cust-deployment
  labels:
    app: assignsrvr
  namespace: default
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: assignsrvr
  template:
    metadata:
      labels:
        app: assignsrvr
    spec:
      containers:
        - name: assignsrvrctr
          image: srikanthduvvuri/assignsrvr:latest
          ports:
            - containerPort: 8080
---

# Nodeport service to expose the application

apiVersion: v1
kind: Service
metadata: 
  name: assignsrvc
  namespace: default
spec:
  selector:
    app: assignsrvr
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort