name : Java CI with maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    analyze:
      name: Analyze
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          language: ['java', 'javascript']
      steps:
        - name: Initialize CodeQL
          uses: github/codeql-action/init@v4
          with:
            languages: ${{ matrix.language }}
          
        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v4
         
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 1.11
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'zulu'
            cache: 'maven'
        - name: Build with Maven
          run: mvn clean install
